version: '3.3'

services:
  db:
    image: postgres:15
    container_name: taskmanager_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskmanager
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d taskmanager"]
      interval: 5s
      timeout: 5s
      retries: 10
  app:
    build: .
    container_name: taskmanager_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    entrypoint: ["dotnet", "TaskManager.WebApi.dll"]
    
#  frontend:
#    build:
#      context: ./task-manager-app  
#    container_name: taskmanager_frontend
#    ports:
#      - "3000:3000"  
#    entrypoint: ["npm", "run", "dev"]